apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-db-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: payment-db-secret
    template:
      data:
        DATABASE_URL: "postgresql://postgres:{{ .password }}@{{ .endpoint }}:5432/payment_db"
        PASSWORD: "{{ .password }}"
        ENDPOINT: "{{ .endpoint }}"
  data:
  - secretKey: password
    remoteRef:
      key: rds-password
      property: password
  - secretKey: endpoint
    remoteRef:
      key: rds-password
      property: endpoint
