apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-redis
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: inventory-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-redis
  template:
    metadata:
      labels:
        app: inventory-redis
    spec:
      nodeSelector:
        workload_type: stateful
      containers:
      - name: inventory-redis
        image: redis:7-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-redis
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: inventory-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
