apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serviceName: "order-db"
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      nodeSelector:
        workload_type: stateful
      containers:
      - name: order-db
        image: postgres:15
        args: ["-c", "wal_level=logical", "-c", "max_replication_slots=10", "-c", "max_wal_senders=10"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "order_db"
        volumeMounts:
        - name: order-db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: order-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: order-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
